### ISSUE TITLE
[REQUEST] New Feature

### ISSUE THREAD

**Issue by rafaelmaribojoc** [ptrstn/dailyblink#15]
Good day sir, I appreciate this wonderful tool of yours and now I fancy some features to not only download dailyblinks but also be able to download every book when you have a premium subscription if you have free time and if it's okay:> If you mind then thank you so much❤

(I always head here every time I open Github because it's nice HAHAHAHA)

**Comment by fugohan** [comment]
This could be helpful: 

https://github.com/leoncvlt/blinkist-scraper

**Comment by ptrstn** [comment]
I have already implemented something similar in this project, but unfortunately this method doesn't work anymore because of the Cloudflare protection. 

If you want to check the source code see: https://github.com/ptrstn/dailyblink/blob/f0cf5e458d760d48df8c3fdbf1a6c944d93e7c66/dailyblink/blinkist.py

**Comment by ptrstn** [comment]
I think I can make it working again with the use of:
- https://github.com/ultrafunkamsterdam/undetected-chromedriver
- https://github.com/cryzed/Selenium-Requests

Need to do further experiments first
